version: '3'
services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: liquid_api
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:3.0.5
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis/data

  web:
    build: .
    links:
      - postgres
      - redis
      - mailcatcher
    volumes:
      - .:/liquid_api
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'


  # sidekiq:
  #   build: .
  #   command: bundle exec sidekiq -C config/sidekiq.yml
  #   links:
  #     - postgres
  #     - redis
  #   volumes:
  #     - .:/liquid_api
  #   env_file:
  #     - .env

volumes:
  postgres-data:
  redis-data:
