version: '3'
services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: liquid_api
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:3.0.5
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis/data

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml -r ./liquid_api.rb
    links:
      - postgres
      - redis
      - mailcatcher
    volumes:
      - .:/liquid_api
      - .:/usr/src/app
      - bundle_cache:/bundle
    env_file:
      - .env
    environment:
      - MAILCATCHER_URL=mailcatcher

  web: &app_base
    build: .
    links:
      - postgres
      - redis
      - mailcatcher
    volumes:
      - .:/liquid_api
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - MAILCATCHER_URL=mailcatcher
    volumes:
      - .:/usr/src/app
      - bundle_cache:/bundle
    tty: true
    stdin_open: true

  test:
    <<: *app_base
    ports:
      - '5000:3000'
    environment:
      DATABASE_URL: postgresql://liquid_api:password@postgres:5432/liquid_api_test
      RACK_ENV: test

volumes:
  postgres-data:
  redis-data:
  bundle_cache:
