en:
  errors:
    unique?: "must be unique (not already taken)"
    same_password?: "doesn't match password"
    valid_currency?: "should be a valid ISO 4217 currency code"
    is_record?: "doesn't exist in database"
    enough_balance?: "is more than account balance"
    same_currency?: "must have the same currency as the other account"
