en:
  errors:
    unique?: "must be unique (not already taken)"
    same_password?: "doesn't match password"
    valid_currency?: "should be a valid ISO 4217 currency code"
    is_record?: "must exist in database"
    enough_balance?: "must have enough balance"
    same_currency?: "must have the same currency as the other account"
    same_user?: "must be owned by the same user as the other account"
    unique_true?: "must be unique when true"
